name: build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15.15'

      - name: Cache go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Test
        run: |
          cd go/src/infra/tools/git
          go test
      - name: Build
        run: |
          cd go/src/infra/tools/git
          go build

      - name: Test executable
        run: |
          ./go/src/infra/tools/git/git version

      - uses: actions/upload-artifact@v3
        with:
          name: git
          path: go/src/infra/tools/git/git

      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.PULL_REQUEST_APP_ID }}
          private_key: ${{ secrets.PULL_REQUEST_APP_PRIVATE_KEY }}

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          files: go/src/infra/tools/git/git
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
